language: python
addons:
  apt:
    packages:
      - lame
      - libmp3lame-dev
      - libmpg123-dev
      - libvorbis-dev
install: pip install tox
script: tox

jobs:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
      install: pip install tox coveralls
      after_success: coveralls
    - stage: deploy
      python: 3.8
      install: skip
      script: skip
      deploy:
        provider: pypi
        user: fetzerch
        password:
          secure: pzU8Si41xv2nKMvnMVExzGzSUzJhEMSetO09Td+NW6qvr3MmyXJ93EE1wGptnGG5gFNO5ZkqnZSBAWlg7ozDGetA5Ia0/8iPBbmaXfSSJ2dKOSMVDi9wHpftXNbnRQJjABQf+rbIOmWLb8oMOBvY/iElSn1k3qGQFqCRmSzH58YSXW9sTR0rDuNEQqxpA82PqqLzIcnGLaafJ0a3O5eI/PlkWqDgVxX0596f9CprPIsylxjAv5OgifQm5r5qTP7/VaGXCf/leCUTpxSGoW7z/nlC+Bh8vnnRrL19ccSQVccNCz/MQ/DSfeBWU2o5BuDq97WlvTPnri2iEBlV6IhGxpK4wA0E7fZ2jEPDc4tklgok7rz5bCzQkY0beKkq/8KEWk1j7okviNMFEVIEO4mIMSPBkAmXkXM9ZS0s+5p9pz/4nZ2ZyOe7t5wwuLPy5NsZey6obAj/Q/5G3eNMsLQvbYxgeYduXgJ+2/8BcpRlXk3tg2iVD8oxB2Ojd7LbJ+6Ga+qi9zivmWMVyYCccdbHuOgiiIOP/bWW0Xj1H3s0qV07PN7jyD3a59Pao3Sgx9vJEV9ckzUuCCL0GM3kVl1OwV12zHAVZZsgHCHS4bOsOao4ZrEO0lfCWjPbhJT+WTFmyNyIu0lHKfkOE3b8etRrxDPnsKzrTxuzbb3T2TzLU18=
        on:
          tags: true
